# Generated by Django 3.2.7 on 2021-09-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='planeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('productores', models.CharField(max_length=50)),
                ('texto_apertura', models.CharField(max_length=50)),
                ('personajes', models.ManyToManyField(to='apistarwars.Personaje')),
                ('planetas', models.ManyToManyField(to='apistarwars.planeta')),
            ],
        ),
    ]
