# Generated by Django 3.2.7 on 2021-09-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apistarwars', '0002_rename_articulos_peliculas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='texto_apertura',
            field=models.CharField(max_length=500),
        ),
    ]
