# Generated by Django 3.2.7 on 2021-09-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apistarwars', '0003_alter_peliculas_texto_apertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='texto_apertura',
            field=models.CharField(max_length=1000),
        ),
    ]
